name: Update OISD Domains

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-domains:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download the domains file
      run: wget https://big.oisd.nl/domainswild -O oisd_big.txt

    - name: Modify the file
      run: sed -i 's/\*\./+./g' oisd_big.txt

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update domainswild.txt with modified entries"
        file_pattern: oisd_big.txt
