name: Auto Update

on:
  schedule:
    - cron: '0 * * * *' 
  workflow_dispatch:

jobs:
  update-domains:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download the oisd_big.txt file
      run: wget https://big.oisd.nl/domainswild -O oisd_big.txt

    - name: Modify the oisd_big.txt file
      run: sed -i 's/\*\./+./g' oisd_big.txt

    - name: get data
      id: extract_info
      run: |
        entries=$(grep -oP '(?<=^# Entries: ).*' oisd_big.txt)
        last_modified=$(grep -oP '(?<=^# Last modified: ).*' oisd_big.txt)
        echo "entries=$entries" >> $GITHUB_ENV
        echo "last_modified=$last_modified" >> $GITHUB_ENV

    - name: Update README.md
      run: |
        last_update=$(date '+%d-%m-%y')
        sed -i "s|\[oisd_big\](https://big.oisd.nl/domainswild) \| \*\*.*\*\* \| .*|\[oisd_big\](https://big.oisd.nl/domainswild) \| **$last_update** \| ${{ env.entries }}|" README.md
        git add README.md
      
    - name: Download the oisd_small.txt file
      run: wget https://small.oisd.nl/domainswild -O oisd_small.txt

    - name: Modify the oisd_small.txt file
      run: sed -i 's/\*\./+./g' oisd_small.txt

    - name: Download the oisd_nsfw.txt file
      run: wget https://nsfw.oisd.nl/domainswild -O oisd_nsfw.txt

    - name: Modify the oisd_nsfw.txt file
      run: sed -i 's/\*\./+./g' oisd_nsfw.txt

    - name: Download the ABPindo.txt file
      run: wget https://fastly.jsdelivr.net/gh/ABPindo/indonesianadblockrules@master/subscriptions/domain.txt -O ABPindo.txt

    - name: Modify the ABPindo.txt file
      run: sed -i 's/^/+./g' ABPindo.txt

    - name: Set commit message with timestamp
      id: set-message
      run: echo "Update on $(date '+%Y-%m-%d %H:%M:%S')" > commit_message.txt

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add oisd_big.txt ABPindo.txt oisd_small.txt oisd_nsfw.txt
        git commit -F commit_message.txt || echo "No changes to commit"
        git push
